"use client";

import { useState } from "react";
import type { ResearchReport } from "@/lib/types";

export default function ResearchPanel({
  ac,
  onClose,
}: {
  ac: number;
  onClose: () => void;
}) {
  const [report, setReport] = useState<(ResearchReport & { cached?: boolean }) | null>(null);
  const [loading, setLoading] = useState(false);

  async function run(force = false) {
    setLoading(true);
    try {
      const res = await fetch("/api/research", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ac, force }),
      });
      const data = await res.json();
      if (res.status === 429) {
        setReport({
          generatedBy: "rate limited",
          workSummary: data.message ?? "Rate limit reached. Please try again later.",
          integrityScan: "",
          promiseVsResult: "",
          sources: [],
        });
        return;
      }
      setReport(data);
    } catch {
      setReport(null);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={onClose}>
      <div
        className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl scrollbar-thin dark:bg-slate-800"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-slate-200 p-5 dark:border-slate-700">
          <div>
            <h2 className="text-lg font-bold">MLA Research Agent</h2>
            <p className="text-sm text-slate-500 dark:text-slate-400">
              Scans gathered sources for the MLA&apos;s work, integrity flags, and
              promise-vs-result.
            </p>
          </div>
          <button
            onClick={onClose}
            className="rounded-full bg-slate-100 px-3 py-1 text-lg leading-none hover:bg-slate-200 dark:bg-slate-700 dark:hover:bg-slate-600"
            aria-label="Close"
          >
            ×
          </button>
        </div>

        <div className="p-5">
          {!report && !loading && (
            <button
              onClick={() => run(false)}
              className="w-full rounded-xl bg-brand py-3 font-semibold text-white hover:bg-brand-dark"
            >
              ▶ Run research agent
            </button>
          )}

          {loading && (
            <div className="flex flex-col items-center gap-3 py-10 text-slate-500">
              <div className="h-8 w-8 animate-spin rounded-full border-4 border-slate-200 border-t-brand" />
              <p>Analysing sources…</p>
            </div>
          )}

          {report && (
            <div className="space-y-4">
              <Section title="Work done (last term)" body={report.workSummary} />
              <Section
                title="Integrity / corruption scan"
                body={report.integrityScan}
                tone="warn"
              />
              <Section
                title="Promise vs result"
                body={report.promiseVsResult}
              />
              <div>
                <h3 className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-500">
                  Sources
                </h3>
                <ul className="space-y-1 text-sm">
                  {report.sources.map((s) => (
                    <li key={s.url}>
                      <a
                        href={s.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-brand hover:underline"
                      >
                        {s.title} ↗
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
              <p className="text-[11px] text-slate-400">
                Generated by {report.generatedBy}
                {report.cached ? " · cached" : " · freshly generated"}. Allegations
                are reported as allegations, not established facts.
              </p>
              <button
                onClick={() => run(true)}
                className="rounded-md border border-slate-300 px-3 py-1 text-sm hover:bg-slate-50 dark:border-slate-600 dark:hover:bg-slate-700"
              >
                Regenerate
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  body,
  tone,
}: {
  title: string;
  body: string;
  tone?: "warn";
}) {
  return (
    <div
      className={`rounded-xl border p-4 ${
        tone === "warn"
          ? "border-amber-200 bg-amber-50 dark:border-amber-900/60 dark:bg-amber-950/30"
          : "border-slate-200 bg-slate-50 dark:border-slate-700 dark:bg-slate-700/40"
      }`}
    >
      <h3 className="mb-1 text-sm font-semibold text-slate-700 dark:text-slate-200">{title}</h3>
      <p className="text-sm leading-relaxed text-slate-600 dark:text-slate-300">{body || "—"}</p>
    </div>
  );
}
